services:

  db:
    image: postgres
    restart: always
    volumes:
      - "./pkg/database/tablesql:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: orders
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
