### PUT update status by order_id
PUT localhost:8181/orders/1/status
Content-Type: application/json

{
 "status": "SENDING"
}

### PUT update status by order_id when order_id is not found
PUT localhost:8181/orders/255555/status
Content-Type: application/json

{
  "status": "PENDING"
}
