ServerPort: "8181"
Database:
  Hostname: "localhost"
  Port: "5432"
  Username: "postgres"
  Password: "example"
  DatabaseName: "orders"
  MaxPoolConnection: 5
  MinPoolConnection: 2
  Timezone: "Asia/Bangkok"
Timeout: 5